### ISSUE TITLE
Make a release? (at least in `mirage-dev`)

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-bootvar-xen#1]

**Comment by MagnusS** [comment]
Yes, good idea :-)

**Comment by avsm** [comment]
This has gone out to opam-repository -- its a good idea to move it to the mirage/ org I think, as it's quite a core library.

**Comment by avsm** [comment]
(that's not a block to merging 0.1 into opam)

**Comment by MagnusS** [comment]
v0.2 is now available in opam
