### ISSUE TITLE
Release the missing cmdline xenstore key fix

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-bootvar-xen#15]
See [mirage/mirage#488] where this was the root cause of a VM failing to boot on Xen with `xl`. Note that we thought the `cmdline` key would only be missing on platforms like XenServer, but the failure was also observed with the vanilla `xl` toolstack.

**Comment by MagnusS** [comment]
Thanks - looks like the issue is more common. I've released 0.3.1 with the fix (Opam PR: https://github.com/ocaml/opam-repository/pull/5561)

**Comment by djs55** [comment]
Thanks!
