### ISSUE TITLE
Dont raise Not_found or log errors to stderr

### ISSUE THREAD

**Issue by avsm** [mirage/mirage-bootvar-xen#2]
The `get` shouldn't raise `Not_found`, as that will inevitably leak.  Similarly with the boot parameters being malformed.

However, this could be the perfect excuse to use @dbuenzli's new Rresult library: http://erratique.ch/software/rresult/doc/Rresult.html#usage

**Comment by MagnusS** [comment]
This should be partially fixed now. `get` returns `string option` and the new function `get_exn` throws `Parameter_not_found`. I changed `create` to return `['Ok of t | 'Error of string]`.

I'll take a look at Rresult now.

**Comment by hannesm** [comment]
thanks to @MagnusS, this was fixed in mirage-bootvar-xen.  There are two functions right now, `get : t -> string -> string option` and `get_exn : t -> string -> string`.  closing, please reopen if you disagree that this is fixed.
